# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170318_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='defalutProfileImg.jpg', upload_to='profile'),
        ),
    ]
