# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohmyroutine', '0004_auto_20170319_1550'),
        ('myroutine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='writer',
            new_name='activist',
        ),
        migrations.AddField(
            model_name='calender',
            name='routine_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ohmyroutine.Routine'),
        ),
    ]
