# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myroutine', '0005_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
