# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcheck',
            name='check',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='meallike',
            name='like',
            field=models.BooleanField(default='False'),
        ),
    ]
