# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20170527_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcheck',
            name='check',
        ),
        migrations.RemoveField(
            model_name='meallike',
            name='like',
        ),
    ]
