# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20170527_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='meal'),
        ),
    ]
