# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='kcal',
            field=models.IntegerField(default=100),
        ),
    ]
