# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_meal_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favor',
            field=models.IntegerField(default=0),
        ),
    ]
