# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_meal_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcheck',
            name='meal_date',
            field=models.CharField(default='2017-01-01', max_length=100),
        ),
    ]
