# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohmyroutine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='id',
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
