# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohmyroutine', '0002_auto_20170319_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_name', models.CharField(max_length=40)),
                ('Exercise_movie', models.FileField(upload_to='uploads/')),
                ('Exercise_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
