# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohmyroutine', '0003_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInRoutine',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_count', models.CharField(max_length=20)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_detail',
            new_name='exercise_detail',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_movie',
            new_name='exercise_movie',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_name',
            new_name='exercise_name',
        ),
        migrations.AddField(
            model_name='exerciseinroutine',
            name='exercise_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ohmyroutine.Exercise'),
        ),
        migrations.AddField(
            model_name='exerciseinroutine',
            name='routine_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ohmyroutine.Routine'),
        ),
    ]
